name: life_line
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  card_swiper : ^3.0.0
  flutter_spinkit: ^5.2.0
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
         
    - family: Zodiak
      fonts:
        - asset: assets/fonts/Zodiak-Bold.ttf
          weight: 700

  assets:
       - assets/pics/doc1.png
       - assets/pics/doc2.png
       - assets/pics/doc3.png
       - assets/icons/Vector.png
       - assets/icons/google.png
       - assets/icons/facebook.png
       - assets/icons/apple.png
       - assets/icons/festive.png
       - assets/background/bg.png
       - assets/background/bg2.png
       - assets/background/bg3.png

 